name: this-is-the-workflow-name
run-name: this-is-the-run-name
on: [push]
jobs:
  job-1-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install ci
        working-directory: src/azure-sa
      
      - name: Linting
        run: npm run lint
        working-directory: src/azure-sa

  
  job-2-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install ci
        working-directory: src/azure-sa
      - name: Testing
        run: npm test
        working-directory: src/azure-sa